# proxy-config-memory.yaml
# Configuration for memory storage

# Default tenant to use when tenant_id is not found
default_tenant: "10000000-0000-0000-0000-000000000000"

# Tenant configurations
tenants:
  10000000-0000-0000-0000-000000000000:
    store_type: "memory"

     
    